### ISSUE TITLE
Levant fails if there are no changes

### ISSUE THREAD

**Issue by sebastianhendrickx** [jrasell/levant#186]
The latest version of levant (0.1.1) has introduced a new feature where a plan is run before a actual deploy. If there are no changes, the  command returns a false (exit code 1).

Wouldn't it be better to output a message saying there were no changes and exit with exit code 0? Since doing a deployment while there are no changes is technically not a error in my opinion.

**Comment by stevenscg** [comment]
I am about to update to version 0.1.1 and have been wondering the same thing. I'd be interested in the backstory regarding this change / feature.

Our CI/CD workflow that uses levant and containers tagged with the SHA of the commit. Our devs know that they can trigger a new build from that system to redeploy their applications. In reality though, Nomad will not make any changes if nothing in the job file has changed (and the appropriate number of allocations are still running). I am contemplating using the build number from the CI/CD system as an additional meta tag on the job to a) avoid the run being marked as failed because levant exited with 1, and b) ensure that nomad sees it as a new build / deploy.

**Comment by sebastianhendrickx** [comment]
For us, our CI/CD fails because of this, I reverted to 0.1.0. 

We try and keep the pipelines as straight forward as possible and rely on nomad to know whether it needs to do a deploy or not since when running a nomad run, it won't deploy if the what you're trying to deploy doesn't differ from what's actually deployed already.

I feel like adding something in levant that basically does the same as nomad does (if no changes then do nothing) but in this case fails with a non zero exit status is not really necessary.

This basically means a couple of things:
 - Change your pipeline so it handles non zero exit codes making it more complex
 - Adding the meta like you described which basically translates to a force deploy even if there are no changes and kind of moves away from the way nomad is intended to be used.

**Comment by stevenscg** [comment]
@sebastianhendrickx So ideally, you would prefer that this behavior be opt-in (via cli flag, etc), right?

**Comment by sebastianhendrickx** [comment]
Exactly

**Comment by jrasell** [comment]
@sebastianhendrickx and @stevenscg thanks for the discussion points above. my initial thoughts were that a deployment with no changes is an issue and something I would like my build pipeline to inform me of with a failure. 

One of the key points made above `rely on nomad to know whether it needs to do a deploy or not` makes perfect sense to me and so I am happy to change the behaviour as a result. The question here being do we want the original behaviour where no changes will log as such and exit 0; or a flag as described above. I am happy with either but conscious of adding too many flags; although this should be made easier once I add the ability to use a config file for Levant config items such as Nomad address etc.

**Comment by matth** [comment]
Hello, I would like to add my support for the ability to exit 0 even where there are no changes. 

I have no preference for the implementation (--flag or otherwise) but at the moment the current behaviour causes our CI jobs to fail.

**Comment by matth** [comment]
Thanks, an opt in flag would be great for us - Levant is a much appreciated bit of software.

**Comment by sebastianhendrickx** [comment]
Thanks!
