### ISSUE TITLE
Failure Introspection leaves me wanting more

### ISSUE THREAD

**Issue by jolexa** [jrasell/levant#26]
Hello, I was really hopeful that `-log-level debug` would assist me, but it still leaves me wanting more. I don't know how to get anymore info out of levant in this case. Any ideas?

```
20:49:09.479 [DEBUG] levant/deploy: running dynamic job count updater for job sre-example-app
20:49:09.485 [INFO] levant/deploy: using dynamic count 3 for job sre-example-app and group production
20:49:09.485 [INFO] levant/deploy: triggering a deployment of job sre-example-app
20:49:09.495 [DEBUG] levant/deploy: beginning deployment watcher for job sre-example-app
20:49:09.500 [DEBUG] levant/deploy: Nomad returned an empty deployment for evaluation 7d96d04e-92f6-f9be-e4cc-6e0c7d904d1e; retrying
20:49:11.521 [DEBUG] levant/deploy: deployment 1ac0c116-f987-af95-be37-292f8842c707 running for 2.02595389s
20:49:11.521 [ERROR] levant/deploy: deployment 1ac0c116-f987-af95-be37-292f8842c707 has status failed, Levant will now exit
20:49:11.529 [ERROR] levant/command: deployment of job sre-example-app failed
```

**Comment by jrasell** [comment]
Hey @jolexa; it could be because I don't currently reflect through the allocation errors which is something I have been meaning to update and only use a case statement to catch the messages. I will have a look into this tomorrow and should have an update early UK time to test out. In the meantime if you do have the output of manually checking the `alloc-status` log that would help me ensure I fix the right thing.

**Comment by jolexa** [comment]
I understand what you are saying. Unfortunately, I cannot reproduce this issue today. One thing that changed is that I _think_ there was a bad deployment that nomad couldn't update and today I "stopped" the dead job. I'm pretty new to nomad and not sure what happened.
