### ISSUE TITLE
Levant logging should add timestamp

### ISSUE THREAD

**Issue by jrasell** [jrasell/levant#68]
When running Levant from the CLI; it outputs a stream of text which looking at retrospectively can be annoying without the timestamp reference. Levant should therefore be updated to include a timestamp in the logging output to provide greater clarity to users.

**Comment by dansteen** [comment]
any objection to my taking a look at working on this?

**Comment by jrasell** [comment]
not at all @dansteen, would appreciate the help. my idea is essentially to have the log format like:

```
2017/12/10 09:21:03 [INFO]
```

Open to discussion of course though.

**Comment by dansteen** [comment]
Sounds reasonable.  I notice that the timestamp in the allocation information includes the timezone:
```
01/03/18 17:30:58 EST  Terminated             Exit Code: 0
```
Is that something you would want to have replicated?

**Comment by jrasell** [comment]
I agree with you on timezone based on where levant is running. It would be confusing and also annoying especially in deployments to multi-region clusters.

**Comment by dansteen** [comment]
[One other question regarding this ( I know, it's supposed to be a simple task).   There are two different types of messages that that levant reports.  The first is messages that levant generates (things like connection errors, or options errors), and the second is messages that are generated by nomad on the nomad servers.   When printing messages reported by levant, we can just print the local timestamp.   However, when printing messages generated by nomad,  we can either print the local timestamp or we can print the timestamp that the event occured at.   

On the one hand, printing timestamps from the server could lead to very confusing log messages if the server and the client machine are out of sync (since the messages could appear out of order).  On the other hand, using the timestamp from the local machine could lead to difficult debugging when looking at the actual job with the nomad tools.   

I'm leaning toward having the output of levant be self-consistant as much as possible even if it causes some drift from what the server shows.   Any preferences on this?

**Comment by jrasell** [comment]
I prefer Levant being self-consistent; I think having Levant log two messages in two different timezone settings would be confusing as hell.
